name: eTracker
description: An Expense Tracking app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # database storage
  sqflite: ^2.0.0+3
  # format DateTime
  intl: ^0.17.0
  # display todos in grids
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  # for displaying list of expense
  sticky_grouped_list: ^2.1.0
  # curved_bottom_navigation_bar
  curved_navigation_bar: ^1.0.1
  # pie_chart for circular stats
  pie_chart: ^5.3.1
  # extra icons
  community_material_icon: ^5.9.55
  # fonts
  font_awesome_flutter: ^10.1.0
  # dropdown
  dropdown_button2: ^1.5.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# read the comments to see how to import fonts/icons
flutter:

  uses-material-design: true

  assets:
     - lib/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
